# Generated by Django 3.1.3 on 2020-12-01 17:37

import datetime

from django.db import migrations
from django.db import models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True, unique=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2020, 12, 1, 17, 37, 41, 669478, tzinfo=utc
                        )
                    ),
                ),
                ("nr_likes", models.IntegerField(default=0)),
            ],
        ),
    ]
