# Generated by Django 3.1.4 on 2020-12-01 18:32

from django.db import migrations
from django.db import models

import applications.blog.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_auto_20201201_2122"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(default=applications.blog.models._now),
        ),
    ]
