# Generated by Django 3.1.4 on 2020-12-07 18:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_auto_20201201_2132"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="nr_views",
            field=models.IntegerField(default=0),
        ),
    ]
